# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
include: ["_pages"]
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - venv/   

# Site Meta data
title: HifumiWeb
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: s1230tats
github_username:  stats1230

# LaTeX
math:
  provider: "katex"

# Site author
author:
  name     : Shunsuke Tatsuno
  avatar   : "/assets/images/IMG_0371.jpg"
  bio      : "A master's degree student at the Graduate School of Law, Hitotsubashi University."
  location : "Tokyo, Japan"
  links:
    - label: "X (Twitter)"
      icon : "fa-brands fa-square-x-twitter"
      url  : "https://x.com/S1230Tats"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/stats1230"

# Footer
footer:
  links:
    - label: "X (Twitter)"
      icon : "fa-brands fa-square-x-twitter"
      url  : "https://x.com/S1230Tats"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/stats1230"